apiVersion: v1
kind: Service
metadata:
  name: redis-monitor-svc
  namespace: default
  labels:
    app: redis
    k8s-app: redis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  ports:
  - port: 9121
    targetPort: 9121
    protocol: TCP
    name: metrics
  selector:
    app: redis