apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - protocol: TCP
      port: 6379
      name: redis
  selector:
      app: redis
      role: master
      tier: backend