apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    app: redis
    name: sentinel
    role: service
spec:
  ports:
    - protocol: TCP
      port: 26379
      name: sentinel
  selector:
    app: redis
    redis-sentinel: "true"