apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
    - protocol: TCP
      port: 6379
      name: slave
  selector:
      app: redis
      role: slave
      tier: backend