apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: csye7374
spec:
  maxReplicas: 100
  minReplicas: 2
  targetCPUUtilizationPercentage: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csye7374