apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: csye7374
    tier: csye7374
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: csye7374
    tier: csye7374